FriendsOfREDAXO/geolocation

composer.json
Reverts christophboecker/geolocation#15
=> Revert "Vendor Vendor mjaschen/phpgeo"

CHANGELOG.md, install.php, package.yml
=> Bugfix in install.php: temporäre SQL-Datei anlegen

boot.php
Reverts FriendsOfREDAXO/geolocation#44
=> Revert "possible fix for undefined constant"

CHANGELOG.md, boot.php, docs/devphp.md, install.php, lib/Cronjob.php, uninstall.php, update.php
Änderung des Klassennamens sowie des Dateinamens; Anpassen aller Referenzen in anderen Dateien des Addons
Zugleich Redaxos php_cs_fixer-Styles angewandt.
=>  Klasse cronjob in Cronjob geändert

CHANGELOG.md, boot.php, docs/devphp.md, lib/Cache.php, lib/Tools.php, lib/yform/dataset/layer.php, lib/yform/dataset/mapset.php
Klassennamen und Dateinamen in Tools geändert. Alle Dateien, die darauf aufsetzen, ebenfalls geändert. 
Bei der Gelegenheit auch Redaxos php-cs-fixer drüber laufen lassen.
=> Klasse tools in Tools geändert

pages/config.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> pages/config.php: Rexstan-Überarbeitung, Code-Style

boot.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> boot.php: Rexstan-Überarbeitung, Code-Style

update.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> update.php: Rexstan-Überarbeitung, Code-Style

install.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> install.php: Rexstan-Überarbeitung, Code-Style

ytemplates/geolocation/value.choice.check.tpl.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> value.choice.check.tpl.php: Rexstan-Überarbeitung, Code-Style

fragments/geolocation_rex_map.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> geolocation_rex_map.php: Rexstan-Überarbeitung, Code-Style

docs/devphp.md, docs/install.md, install.php, lib/ConfigForm.php, pages/config.php
Klassenname anpepasst, Dateiname passend dazu umbenannt, Referenzen in anderen Dateien aktualisiert
=> Klasse config_form umbenannt in ConfigForm

CHANGELOG.md, lib/ConfigForm.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- dead code
=> Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, lib/Tools.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/Tools.php: Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, lib/Exception.php
=> lib/Exception.php: Code-Style

CHANGELOG.md, lib/Cache.php
Rexstan-Überarbeitung, Code-Style
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/Cache.php: Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, boot.php, lib/yform/dataset/mapset.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/yform/dataset/mapset.php: Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, lib/calc/Math.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/calc/Math.php: Rexstan-Überarbeitung, Code-Style

lib/calc/Point.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/calc/Point.php: Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, lib/InvalidParameter.php, lib/calc/Box.php, lib/calc/Point.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/calc/Box.php: Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, install/tableset.json, update.php
Änderungen in `tableset.json` und `update.php` nachgezogen (siehe #86)
=> Klasse "layer" in "Layer" geändert

CHANGELOG.md, install/geolocation.js
=> Bugfix Colorcodes excapen

CHANGELOG.md, docs/devjs.md
=> Übersicht der Default-Werte aktualisiert

CHANGELOG.md, install/geolocation.js
Es muss wohl `encodeURIComponent` sein und nicht `encodeURI`.
=> SvgIcon-Farben mit encodeURIComponent escapen

CHANGELOG.md, lib/asset_packer.php
PR #107 benötigt das als Vorleistung
=> AssetPacker für Darkmode erweitert

package.yml
=> Basis-Permission hinzugefügt

CHANGELOG.md, install/geolocation_be.js, lib/yform/value/layerselect.php
Bei PR #107 hab ich zwei falsche Dateien hochgeladen. Als Folge gab es Probleme in der Verwaltung der Layer im Layerset. Der PR sollte das Problem lösen.
=> Layerset/Mapset: Probleme bei Feldverwaltung und Speichern behoben. 

update.php
Versehentlich in #113 gelöscht statt nur den überflüssigen Code zu entfernen
=> update.php wiederhergestellt

install/geolocation_be.js
Für alle Fälle statt `stopPropagation`
=> stopImmediatePropagation

lib/yform/value/layerselect.php
=> Behebt Fehler bei leerer Choice-Rückgabe

lib/api_testurl.php, lib/yform/dataset/Layer.php
Reverts FriendsOfREDAXO/geolocation#129
=> Revert "Use socket_proxy if set"

CHANGELOG.md, lib/yform/dataset/Mapset.php
=> setColumnFormat kaskadiert

lib/api_testurl.php, lib/yform/dataset/Layer.php
added Proxy Property: @debagel
=> Update api_testurl.php CURL: Proxy Property

lib/yform/dataset/Layer.php
für `rex_addon...` wurde impliziet `..namespace..\rex_addon`angenommen; `use rex_Addon`ergänzt
=> Namespace gefixed

CHANGELOG.md, lib/Layer.php, package.yml
=> Problem mit NULL-Value in Layer::verityLang behoben.

lib/asset_packer.php
fixes #142
bin gerade wieder bei einem erneuten Versuch dein super AddOn einzusetzen auf dieses Problem gestossen.
Ich habe die zweite Variante aus Gregors Kommentar umgesetzt.
https://github.com/FriendsOfREDAXO/geolocation/issues/142#issuecomment-1517987447
=> make subfolders in web path possible

CHANGELOG.md, package.yml
Letzte Anpassungen für das Beta1-Release
=> 2.5.0-beta1
