lib/asset_packer.php
Ich hatte unter Windows (xampp php8) bei der Installation den Fehler
AddOn geolocation konnte aus folgendem Grund nicht installiert werden:
AssetPacker: "C:\www\myproject\app\redaxo\src\addons\geolocation/install/vendor/leaflet/leaflet.css" not minimized [`C:wwwmyproject ppredaxosrc૝ons¾_stylepluginsredaxoscss_variables` file not found for @import: line: 1, column: 0]! Minificaton stopped. (file C:\www\myproject\app\redaxo\src\addons\geolocation\lib\asset_packer.php line 353)
Die ergänzte Zeile löste bei mir das Problem.
=> Backslash aus Pfad in Schrägstrich ersetzen

lib/yform/dataset/layer.php
Der Originalcode hat bei mir (mehrsprachige Seite, 1. Sprache en) eine Warning hervorgebracht:
Undefined array key "en"
Mit dem Patch kam die Warning nicht mehr zum Vorschein und alles funktioniert super.
Zugegeben, der Originalcode ist sehr viel hübscher.
=> Warning Undefined array key "en" beseitigt

CHANGELOG.md, docs/devgeojson.md, docs/devjs.md, docs/devphp.md, docs/devtools.md, docs/settings.md, install/geolocation.js, lib/yform/dataset/mapset.php
Da das Addon eher als Demo gedacht war, sind einige Konzepte unterentwickelt. Z.B. darf im PHP (`$map->dataset('xyz',$daten)`) ein Darstellungstool nur einmal eingebaut werden. JS-seitig werden die Tools als Array verwaltet, also ohne jeden Namensbezug. Dieser PR soll die Designschwäche beheben:
- Tools dürfen merhrfach zugeordnet werden. Dazu wurde einfach die Namenskonvention erweitert.
- Die Identifizierbarkeit der Tools in eigenem, ergänzenden JS wird ermöglicht
- Tools können ihren aktuellen Wert/Datensatz ausgeben; damit wird Interaktivität zur Karte ("Rückkanal") vorbereitet.
In der geänderten Namenskonvention wird  der Toolname über `«tool»|«suffix»` eindeutig gemacht werden, also angehängtes `|«suffix»`.
Die interne Verwaltung der Tools erfolgt nun als Map-Klasse (nicht mit …
=> Tool-Verwaltung geändert

.gitattributes
Stellt für die Dateitypen yml, json und php Dateiformate sicher:
*.php   text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=4 diff=php
*.json  text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=4
*.yml   text eol=lf whitespace=blank-at-eol,blank-at-eof,space-before-tab,tab-in-indent,tabwidth=4
Das ist so eins zu eins aus der .gitattributes des REDAXO-Core.
=> gitattributes: Übernahme der REDAXO-Core-Einstellung

boot.php, install.php, lib/config_form.php
1) Dreht PR #44 zurück, das war nicht die Lösung.
2) Lösung: neue Konstanten sofort setzen (`define(...)`, damit sie beim Kompilieren der Assets direkt verfügbar sind.
Erklärung: einige Werte werden bei der Installation als Konstanten direkt in die boot.php geschrieben. Anschließend kompiliert die Installation die Assets neu zusammen, benötigt dabei z. Zt. zwei der Konstanten (KEY_MAPSET, KEY_TILES). Da hier die boot.php noch nicht ausgeführt wurde, die Konstanten also fehlen, gibt es die übliche Fehlermeldung im Log ("KEY_MAPSET not defined, assumed 'KEY_MAPSET'" oder so). Der Code st nun so geändert, dass die Konstanten auch sofort in der Installation aktiviert werden. 
Danke für den Hinweis an @AndiLeni und an @alxndr-w für´s Aufwecken
=> Installation: Konstanten werden nicht gesetzt

CHANGELOG.md, package.yml
Aus irgend einem Grunde ist in 1.0.1. nicht das drin, was in Github an Dateien vorliegt. 1.0.2 soll das beheben, indem ein neues Release erzeugt wird. Inhaltlich ist sonst nichts geändert (außer changelog und package)
=> Ersetzt fehlerhaftes 1.0.1

pages/index.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> pages/index.php: Rexstan-Überarbeitung, Code-Style

pages/yform.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> pages/yform.php: Rexstan-Überarbeitung, Code-Style

docs/example/geolocation_div.php
Rexstan-Überarbeitung, Code-Style
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> geolocation_div.php: Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, lib/api_clearcache.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=>  Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, lib/Cronjob.php
Rexstan-Überarbeitung, Code-Style
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/Cronjob.php: Rexstan-Überarbeitung, Code-Style

CHANGELOG.md, lib/InvalidParameter.php
Rexstan-Überarbeitung, Code-Style
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
=> lib/InvalidParameter.php: Rexstan-Überarbeitung, Code-Style

lib/yform/dataset/layer.php
parent::getValue($key) bzw. __get  liefert auch für Datenbankfelder vom Typ int immer einen String. Somit z.B. `1===$this-online` immer false, auch wenn `online=1` ist. getValue ist nun so überschrieben, dass vorgesehene int-Felder einen Typecast auf int haben.
=> Workaround für Typecast-Problem aus 'class dataset'

CHANGELOG.md, lib/InvalidParameter.php, lib/calc/DMS2.php
- Code-Style
- RexStan
- Level 8
- PHP
- 8.0
- 8.1
- 8.2
- Extensions
- Strict-Mode
- phpstan-dba
- deadcode
- Fehlermeldungen über `InvalidParameter` ausgeben
- Doppelten Code ggü Parent-Klasse bereinigt
=> lib/calc/dms2.php: Rexstan-Überarbeitung, Code-Style, etc.

lib/yform/dataset/Mapset.php
Die Annahme, dass `protected array $mapDataset = [];` und `protected array $mapAttributes = [];` in jeder neuen Instanz ein leeres Array initialisiert, ist wohl falsch. Daher expliziet ein [] mit der get-Methode zuweisen.
Ansonsten werden bei Seiten mit mehreren Karten Attribute und Dataset-Inhalte ungewollt weitergereicht.
=> Datensatz-Initialisierung

CHANGELOG.md, install.php, install/tableset.json
Bei längeren Attributions / Copyright-Angaben z.B. durch viel HTML (a href title ... ) kommen 191 Byte schnell an die Grenze. Daher in `text` geändert.
=> Feld "Layer|attribution" von "varchar(191)" in "text" geändert

CHANGELOG.md, install/dataset.sql
- OSM ist nun Mapset 1 und damit default. 
- Attribution-Texte (Copyright) geändert
- Radwege-Overlay "CyclOSM" gibt es so nicht mehr. Ersetzt durch "Waymarked Trails: Radwege".
closes #96
=> Dataset bereinigt und aktualisiert

CHANGELOG.md, install.php, lang/de_de.lang
Bisher wurde beim Demo-Import der Tabellen-Prefix expliziet angeglichen. Der Code dazu wurde entfernt; das läuft nun impliziet beim Import über %table_prefix%
=> input.php vereinfacht

CHANGELOG.md, lib/yform/dataset/Layer.php
Ansonsten sind URLs mit `@2x` nicht möglich.
=> @-Zeichen in URLs erlauben

lib/api_testurl.php, lib/yform/dataset/Layer.php
Use socket_proxy setting for curl request to enable using a proxy for fetching map tiles
=> Use socket_proxy if set

CHANGELOG.md, lib/yform/dataset/Layer.php, lib/yform/dataset/Mapset.php
Da in YForm-Versionen nach 4.0.4 (GitHub Stand 07.03.2023) die Action-Buttons anders verwaltet werden, sind Anpassungen auch in Geolocation erforderlich. Mit den Änderungen hier werden sowohl die Variante bis 4.0.4 also auch die neue Variante unterstützt.
siehe #130
=> BC in YForm nach 4.0.4 adaptiert

CHANGELOG.md, install/geolocation_be.js
Es geht um die Auswahl der Basiskarten für einen Kartensatz. 
Die Tastaturauswertung war subobtimal (Repeat-Erkennung und so). Es konnte z.B. passieren, dass beim Verschieben der Einträge ein Eintrag in einer Liste mit drei oder Mehr Einträgen immer sofort ans Ende schoben wurde statt nur um eine Position. 
Und die Selektion des aktiven Eintrags per Leertaste war auch eher erratisch.
=> Tastaturunterstützung der Basiskarten-Auswahl verbessert

CHANGELOG.md, lib/yform/value/layerselect.php, package.yml
In dem Fall kam es zu einem Fehler `Unable to rollback, no transaction started before` aus dem Manager. Tatsächlich war die Ursache im Geolocation-Value `layerselect` in der Zeile 99: 
`$this->getParam('manager_dataset')->getValue($this->subField);`
Beim "Speichern" existiert `param['manager_dataset']`, beim "Übernehmen" jedoch nicht, was im Hintergrund zu einem `getValue on null`-Fehler führt.
=> Bugfix beim Speichern mit "Übernehmen"

CHANGELOG.md, lib/yform/dataset/Layer.php, package.yml
Zum besseren Nachvollziehen werden von cUrl gemeldete Fehler in´s Log geschrieben. Auslöser ist eine Rückmeldung im Slack von @TobiasKrais über fehlgeschlagene Tile-Abrufe. Deren Ursache lat nicht in Geolocation, sondern in Verbindungsproblemen des Servers mit dem Tile-Server (CURL ErrNo: 60, Error: server certificate verification failed. CAfile: none CRLfile: none)
=> cUrl-Fehler ins Log schreiben

lib/yform/dataset/Layer.php
In Zeile 509 werden die Klassen rex_loggger und rex_context verwendet, sie waren aber nicht im Namespace.
=> use rex_logger und rex_context

CHANGELOG.md, lib/Layer.php
ab YForm 4.2.1 wird der Value intern als Array statt JSON-string geführt und an CustomValidators übergeben. Nun ist hier in Layer::verifyLang ein Schalter eingebaut, um JSON-String (alt) und Array (neu) zu unterstützen.
closes #153
=> be_table-Problem adaptiert

CHANGELOG.md, package.yml, pages/yform.php
Das Script _pages/yform-php_ fügt den Tabellenprefix `rex_` jetzt selbst an den Tabellennamen an. Entsprechend sind die Tabellennamen in der _package.yml_ nun ohne Prefix.
=> Tabellen-Prefix automatisch setzen (yform.php)

CHANGELOG.md, lib/Layer.php, lib/Mapset.php, package.yml, pages/index.php, pages/yform.php
Anpassung der Namen (z.B. `Layer::YFORM_DATA_LIST`) in die PSR-konforme Schreibweise (z.B. `Layer::epYformDataList`) sowie damit verbundene Anpassungen im Code;
Aufrufe auf "First class callable syntax" umgestellt
=> Methoden-Namen der EP-Callbacks adjustiert

CHANGELOG.md, docs/devmath.md, install.php, lang/de_de.lang
@bitshiftersgmbh meldete Warnings im Sys-Log, die bei der Übertragung von Bildern in Doku-Artikeln entstanden. Es fehle ein `exit;` nachdem die Grafik abgeschickt war, um weitere Ausgaben zu vermeiden, die zu den Warnings führten.
(Diese Änderung ist leider als direkter Commit im Repo gelandet und nicht dem PR zugeordnet. Nur um es der Vollständigkeit halber zu erwähnen.)
@bitshiftersgmbh stellte während der Fehlersuche zu obigem fest, dass versionsabhängige Installationsschritte beim Update u.U. nicht durchgeführt wurden. Der Versionsvergleich (aktuelle Installation vs. Zielversion) funktionierte nicht wie erwartet. Entsprechende Teile der Installation sind nun so umgestellt, dass sie bei Install/Update immer durchlaufen werden, wenn die nötige Änderung noch nicht vorliegt.
=> V2.4 mit Bugfixes (Installation, Doku)

CHANGELOG.md, lib/Layer.php, lib/Mapset.php, package.yml, pages/yform.php
- Implementierung eines Location-Picker zur interaktiven Auswahl einer Position
- Basis ist ein rex_fragment `PickerWidget`
- als YForm-Value `rex_yform_value_geolocation_geopicker`
- als RexForm-Element `PickerElement`
- als Metafeld `PickerMetafield`
- in Modulen via `PickerWidget`
- Erweiterte Dokumentation (insb. "Für Entwickler | PHP: LocationPicker")
- Geocoding mit Nominatim/OSM (via Proxy) im Picker integriert
- Klasse `SqlTools`: 
- liefert Bausteine für SQL-Abfragen z.B. zur Umkreissuche
- einfachere Implementierung der Spatial-Funktionen in SQL-Abfragen
- Dino-Logo hinzugefügt: README.MD und BE-Seite. (Dino by @skerbis)
- Vendor-Update für "mjaschen/phpgeo" aus Version 6.0.0
- Kompatibilität zu YForm 5 hergestellt wg. Wegfall der Plugins
closes #173
closes #176
=> Release 2.5.0 inl. Anpassung an YForm 5
